name: "Build Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup OpenJDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: maven
      - name: Run Tests
        run: mvn -B test
      - name: Build Jar
        run: mvn -B package --file pom.xml
