name: "Build Pipeline"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Tests
        run: mvn -B test
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'PayrollApp'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

  publish-job:
    name: Publish Jar Artifacts
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/payrollapp-*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: PayrollApp
          path: staging
